### ISSUE TITLE
`Call::as_xml_rpc` is `pub(crate)`

### ISSUE THREAD

**Issue by blaenk** [ironthree/dxr#3]
So following up from our previous conversation, I decided to take a quick and dirty shot at literally copy-pasting `client.rs` into my crate, get it building, then adapt it to my needs (SCGI over TCP/UDS).

I got everything working except for `Call::as_xml_rpc()` being `pub(crate)` and so inaccessible to my crate. Curious if this was intentional and what you think about it.

https://github.com/ironthree/dxr/blob/7147b9b703ff9cb884dd72eb5625d5bab65c21ef/dxr_client/src/lib.rs#L153

https://github.com/ironthree/dxr/blob/7147b9b703ff9cb884dd72eb5625d5bab65c21ef/dxr_client/src/call.rs#L48-L50

**Comment by decathorpe** [comment]
There's no reason for it being `pub(crate)` and not `pub` other than ... it was not necessary to make it `pub` before. :)
But given that it's unlikely to change, I can certainly make it `pub` with the next release.

**Comment by decathorpe** [comment]
Published as version 0.5.1:
https://github.com/ironthree/dxr/releases/tag/0.5.1

I think with this (and custom implementations of `request_to_body` and `request_to_result`) you should be set. Let me know if there's something else you need.

**Comment by blaenk** [comment]
Thank you so much!
