### ISSUE TITLE
Add support for rustls

### ISSUE THREAD

**Issue by bahlo** [ironthree/dxr#4]
Hi, I want to use your library on a system without OpenSSL so I need to use rustls. 

Could we add a flag to get reqwest to use rustls?

**Comment by bahlo** [comment]
Yeah, that's what I was thinking too. I started working on this in https://github.com/bahlo/dxr/tree/add-reqwest-tls-flags, but Cargo is unhappy — feel free to try it 👍

**Comment by decathorpe** [comment]
Can you take a look at this commit and see if that works for you?
https://github.com/ironthree/dxr/commit/beb953c14bd5bdef22236d9ce80255dd5eb10b1e

If it looks good to you, I'll release a new version later.

**Comment by bahlo** [comment]
Hi, yes that works! Thanks for taking care of this so quickly 🙏 Looking forward to the next version

**Comment by decathorpe** [comment]
Thanks for trying it out! I've published v0.5.3 on crates.io: https://crates.io/crates/dxr/0.5.3
